### ISSUE TITLE
when try to build test app from branch test/app fails

### ISSUE THREAD

**Issue by AhmedKhattab95** [luncliff/NdkCamera#2]
when try to build test app from give this errors

> ERROR: Unable to resolve dependency for ':TestApp@debug/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@debugAndroidTest/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@debugUnitTest/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@release/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@releaseUnitTest/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@debug/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@debugAndroidTest/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@debugUnitTest/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@release/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp
> 
> 
> ERROR: Unable to resolve dependency for ':TestApp@releaseUnitTest/compileClasspath': Could not resolve project :NdkCamera.
> Show Details
> Affected Modules: TestApp

**Comment by luncliff** [comment]
The app branch need to be updated. I will work on it within 2 weeks.

Let me create a new branch for that.

**Comment by luncliff** [comment]
@AhmedKhattab95 , I checked the branch [`test/app`](https://github.com/luncliff/NdkCamera/tree/test/app) and it seems working now. Wish it works for you either.
